import { T } from './tokens';

// Styles UI partagés entre toutes les pages — Thème Bleu & Orange
export const S = {
  main: {
    flex: 1,
    padding: "1.5rem",
    maxWidth: 1200,
    width: "100%",
    margin: "0 auto",
    boxSizing: "border-box",
    overflowX: "hidden",
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: T.navy,
    marginBottom: 4,
    letterSpacing: "-0.02em",
  },
  pageSub: {
    fontSize: 13,
    color: T.textMuted,
    marginBottom: "1.25rem",
  },
  card: {
    background: T.white,
    border: `1px solid ${T.border}`,
    borderRadius: 12,
    padding: "1.25rem",
    marginBottom: "1rem",
    boxShadow: "0 1px 4px rgba(15,43,91,0.06)",
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: T.textPrimary,
    marginBottom: "1rem",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1rem",
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "1rem",
  },
  grid4: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr 1fr",
    gap: "0.75rem",
    marginBottom: "1.25rem",
  },
  metric: {
    background: T.white,
    border: `1px solid ${T.border}`,
    borderRadius: 12,
    padding: "1rem",
    boxShadow: "0 1px 4px rgba(15,43,91,0.06)",
  },
  metricValue: {
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    lineHeight: 1.1,
    marginTop: 4,
  },
  metricLabel: {
    fontSize: 12,
    color: T.textMuted,
  },
  metricSub: {
    fontSize: 11,
    color: T.textMuted,
    marginTop: 2,
  },
  badge: (color, bg) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    fontWeight: 500,
    padding: "2px 8px",
    borderRadius: 20,
    background: bg,
    color: color,
    whiteSpace: "nowrap",
  }),
  btn: (variant = "primary") => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: variant === "primary" ? "8px 18px" : "7px 14px",
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 8,
    border: variant === "primary" ? "none" : `1px solid ${T.border}`,
    background: variant === "primary" ? T.orange : T.white,
    color: variant === "primary" ? T.white : T.textPrimary,
    cursor: "pointer",
    boxShadow: variant === "primary" ? "0 2px 8px rgba(232,101,10,0.25)" : "none",
    transition: "all 0.15s",
  }),
  input: {
    width: "100%",
    padding: "8px 10px",
    fontSize: 13,
    border: `1px solid ${T.border}`,
    borderRadius: 7,
    background: T.white,
    color: T.textPrimary,
    outline: "none",
    boxSizing: "border-box",
  },
  label: {
    fontSize: 12,
    color: T.textMuted,
    marginBottom: 4,
    display: "block",
  },
  formGroup: {
    marginBottom: "0.875rem",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
  },
  th: {
    textAlign: "left",
    padding: "8px 12px",
    fontSize: 11,
    fontWeight: 600,
    color: T.textMuted,
    borderBottom: `1px solid ${T.border}`,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    background: T.bg,
  },
  td: {
    padding: "10px 12px",
    borderBottom: `1px solid ${T.border}`,
    color: T.textPrimary,
    verticalAlign: "middle",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "1rem",
    flexWrap: "wrap",
    gap: 10,
  },
  progressWrap: { width: 90 },
  progressBg: {
    height: 6,
    background: T.grayLight,
    borderRadius: 3,
    overflow: "hidden",
  },
  avatar: (bg, color) => ({
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: bg,
    color: color,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
  }),
  filterBtn: (active) => ({
    fontSize: 12,
    padding: "4px 12px",
    borderRadius: 20,
    border: `1px solid ${active ? T.blue : T.border}`,
    background: active ? T.blueLight : "transparent",
    color: active ? T.navy : T.textMuted,
    cursor: "pointer",
    fontWeight: active ? 500 : 400,
  }),
};
